id: I98E41110
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T09:05:32+00:00'
last_modified: '2022-06-10T05:46:26.715903+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18350
  title: གསུང་འབུམ། བློ་བཟང་བསམ་གཏན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    B3A4:
      image_group_id: I8LS18362
      title: Volume 1 of gsung 'bum/ blo bzang bsam gtan/
      total_pages: 1776
      order: 1
      base_file: B3A4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
